In [13]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv(r"C:\Users\USER\Desktop\Machine_Learning_360V2\data\processed\synthetic_sme_agents_data.csv")
df.head()

,sme_id,business_name,revenue,profit_margin,debt_ratio,collateral_value,marketing_spend,employee_count,age_of_business,sector,...,conversions,target_segment,owner_age,owner_gender,education_level,employment_status,location,eligible_for_funding,default_risk,business_health_score
0,1,SME_1,63049.921922,0.102738,0.170476,560.527308,144.543397,81,1,tech,...,484,low,34,female,bachelor,employed,Other,1,low,37.5
1,2,SME_2,47135.917154,0.139884,0.295319,1157.020852,99.194224,31,10,tech,...,54,low,34,male,highschool,employed,Other,1,low,59.0
2,3,SME_3,68567.289121,0.094531,0.302703,725.535298,129.295442,53,4,services,...,313,high,55,female,none,employed,Mombasa,1,low,31.3
3,4,SME_4,123677.627562,0.128443,0.370895,1310.293284,262.903063,34,15,services,...,20,low,51,female,phd,self-employed,Eldoret,1,low,42.4
4,5,SME_5,45495.409067,0.017447,0.094971,2161.968728,412.520262,38,19,retail,...,430,medium,33,male,phd,self-employed,Mombasa,0,low,42.9

In [15]:
df.columns

Index(['sme_id', 'business_name', 'revenue', 'profit_margin', 'debt_ratio',
       'collateral_value', 'marketing_spend', 'employee_count',
       'age_of_business', 'sector', 'previous_funding_received',
       'previous_funding_amount', 'default_history', 'loan_applications_count',
       'funding_requested_amount', 'expected_roi', 'project_duration_months',
       'business_stage', 'collateral_offered',
       'business_registration_uploaded', 'tax_clearance_uploaded',
       'financial_statements_uploaded', 'tax_registered', 'tax_paid_last_year',
       'licenses_required', 'licenses_up_to_date', 'staff_count',
       'total_payroll', 'cost_per_hire', 'nssf_contribution_percent',
       'nhif_contribution_percent', 'staff_turnover_rate', 'bank_balance',
       'm_pesa_balance', 'pending_invoices', 'paid_invoices',
       'total_customers', 'active_customers', 'repeat_customers',
       'channels_used', 'campaign_spend', 'clicks', 'impressions',
       'conversions', 'target_segment', 'owner_age', 'owner_gender',
       'education_level', 'employment_status', 'location',
       'eligible_for_funding', 'default_risk', 'business_health_score'],
      dtype='object')

In [16]:
df.value_counts()

sme_id  business_name  revenue        profit_margin  debt_ratio  collateral_value  marketing_spend  employee_count  age_of_business  sector         previous_funding_received  previous_funding_amount  default_history  loan_applications_count  funding_requested_amount  expected_roi  project_duration_months  business_stage  collateral_offered  business_registration_uploaded  tax_clearance_uploaded  financial_statements_uploaded  tax_registered  tax_paid_last_year  licenses_required  licenses_up_to_date  staff_count  total_payroll  cost_per_hire  nssf_contribution_percent  nhif_contribution_percent  staff_turnover_rate  bank_balance   m_pesa_balance  pending_invoices  paid_invoices  total_customers  active_customers  repeat_customers  channels_used  campaign_spend  clicks  impressions  conversions  target_segment  owner_age  owner_gender  education_level  employment_status  location  eligible_for_funding  default_risk  business_health_score
2000    SME_2000       38975.656998   0.175245       0.124458    67283.235112      248.516878       32              19               services       0                          68153.501476             0                0                        529191.798794             0.220487      35                       mature          1                   1                               1                       1                              1               0                   3                  1                    22           299681.786394  24640.348957   0.086574                   0.026125                   0.175724             162333.205610  37401.694186    10                18             3650             3260              533               physical       29344.257710    2414    52100        12           low             45         male          phd              self-employed      Kisumu    1                     low           51.1                     1
1       SME_1          63049.921922   0.102738       0.170476    560.527308        144.543397       81              1                tech           0                          103742.202836            0                2                        244358.673030             0.052568      6                        startup         1                   1                               1                       1                              1               1                   4                  1                    47           251740.630056  26865.394255   0.103539                   0.036987                   0.152088             82038.142099   40148.631688    11                27             2387             238               855               physical       12902.135639    2746    38880        484          low             34         female        bachelor         employed           Other     1                     low           37.5                     1
2       SME_2          47135.917154   0.139884       0.295319    1157.020852       99.194224        31              10               tech           0                          486834.380297            0                3                        156122.829362             0.170015      33                       growth          0                   1                               1                       1                              1               1                   4                  1                    43           421476.792751  5602.846808    0.050896                   0.027753                   0.152460             58333.683515   18694.160350    8                 8              3495             872               1841              online         21114.324031    39      62471        54           low             34         male          highschool       employed           Other     1                     low           59.0                     1
3       SME_3          68567.289121   0.094531       0.302703    725.535298        129.295442       53              4                services       1                          150407.499682            0                1                        217582.564789             0.113998      28                       startup         1                   1                               1                       1                              1               1                   3                  1                    21           66306.706128   7570.522957    0.073811                   0.036775                   0.154919             14324.429719   37987.086443    14                12             3955             324               2875              online         46215.043104    220     60868        313          high            55         female        none             employed           Mombasa   1                     low           31.3                     1
4       SME_4          123677.627562  0.128443       0.370895    1310.293284       262.903063       34              15               services       0                          123169.895372            0                5                        366994.530657             0.149236      14                       mature          1                   1                               1                       1                              1               1                   4                  0                    43           200624.461681  49988.950720   0.111476                   0.043776                   0.153862             114535.229426  31088.579961    9                 18             2419             1731              2072              physical       28900.089978    4574    38562        20           low             51         female        phd              self-employed      Eldoret   1                     low           42.4                     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ..
17      SME_17         36676.638757   0.131484       0.227875    78264.019946      82.571053        15              10               beauty         0                          216549.388775            0                0                        910067.846244             0.313608      4                        growth          0                   1                               0                       1                              0               1                   3                  1                    6            141929.448837  32556.786060   0.066755                   0.033696                   0.222129             11110.842073   10507.411013    9                 31             1570             1627              658               online         3311.051072     405     24249        29           medium          39         male          highschool       self-employed      Other     0                     medium        61.0                     1
16      SME_16         40935.402269   0.136432       0.213131    818.960318        435.233742       48              19               agriculture    0                          178392.704035            0                0                        113305.754088             0.108287      34                       startup         0                   1                               1                       1                              1               1                   2                  1                    46           422048.412429  20184.039192   0.104810                   0.044097                   0.120699             143911.859623  26211.792110    0                 9              2565             907               756               physical       30831.938924    3130    26173        325          medium          30         male          highschool       self-employed      Mombasa   1                     low           44.8                     1
15      SME_15         32865.209777   0.208063       0.288140    6115.028539       109.737460       35              9                manufacturing  0                          290142.359208            0                0                        304195.495110             0.234008      25                       growth          1                   1                               1                       1                              1               1                   1                  1                    5            62243.681005   42125.117518   0.083304                   0.045205                   0.117315             107143.410513  45882.144006    5                 35             2577             1144              1319              online         27363.336978    835     47313        166          low             28         male          master           self-employed      Mombasa   0                     low           46.1                     1
14      SME_14         32234.943935   0.084207       0.329802    15386.862213      141.927768       61              18               tech           0                          98720.552932             0                6                        591908.888805             0.184697      28                       mature          0                   1                               0                       0                              1               1                   1                  1                    37           184765.147014  44423.415609   0.108451                   0.020319                   0.111205             131807.810402  30824.526620    0                 28             4583             1267              869               online         2611.941418     1720    7034         106          low             43         female        phd              self-employed      Mombasa   0                     low           52.1                     1
13      SME_13         55436.059171   0.096160       0.152251    4021.521641       135.524163       21              4                tech           0                          89236.599606             0                9                        94188.093435              0.308443      9                        growth          1                   1                               1                       1                              1               1                   1                  1                    37           70845.271255   14906.115495   0.062069                   0.026390                   0.126657             69193.632798   26448.726665    5                 39             922              235               2950              physical       17277.030409    2286    66565        146          medium          24         male          phd              employed           Mombasa   1                     low           68.6                     1
Name: count, Length: 1980, dtype: int64

In [17]:
df.shape

(2000, 53)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 53 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   sme_id                          2000 non-null   int64
 1   business_name                   2000 non-null   object
 2   revenue                         2000 non-null   float64
 3   profit_margin                   2000 non-null   float64
 4   debt_ratio                      2000 non-null   float64
 5   collateral_value                2000 non-null   float64
 6   marketing_spend                 2000 non-null   float64
 7   employee_count                  2000 non-null   int64
 8   age_of_business                 2000 non-null   int64
 9   sector                          2000 non-null   object
 10  previous_funding_received       2000 non-null   int64
 11  previous_funding_amount         2000 non-null   float64
 12  default_history                 2000 non-null   int64
 13  loan_applications_count         2000 non-null   int64
 14  funding_requested_amount        2000 non-null   float64
 15  expected_roi                    2000 non-null   float64
 16  project_duration_months         2000 non-null   int64
 17  business_stage                  2000 non-null   object
 18  collateral_offered              2000 non-null   int64
 19  business_registration_uploaded  2000 non-null   int64
 20  tax_clearance_uploaded          2000 non-null   int64
 21  financial_statements_uploaded   2000 non-null   int64
 22  tax_registered                  2000 non-null   int64
 23  tax_paid_last_year              2000 non-null   int64
 24  licenses_required               2000 non-null   int64
 25  licenses_up_to_date             2000 non-null   int64
 26  staff_count                     2000 non-null   int64
 27  total_payroll                   2000 non-null   float64
 28  cost_per_hire                   2000 non-null   float64
 29  nssf_contribution_percent       2000 non-null   float64
 30  nhif_contribution_percent       2000 non-null   float64
 31  staff_turnover_rate             2000 non-null   float64
 32  bank_balance                    2000 non-null   float64
 33  m_pesa_balance                  2000 non-null   float64
 34  pending_invoices                2000 non-null   int64
 35  paid_invoices                   2000 non-null   int64
 36  total_customers                 2000 non-null   int64
 37  active_customers                2000 non-null   int64
 38  repeat_customers                2000 non-null   int64
 39  channels_used                   2000 non-null   object
 40  campaign_spend                  2000 non-null   float64
 41  clicks                          2000 non-null   int64
 42  impressions                     2000 non-null   int64
 43  conversions                     2000 non-null   int64
 44  target_segment                  2000 non-null   object
 45  owner_age                       2000 non-null   int64
 46  owner_gender                    2000 non-null   object
 47  education_level                 2000 non-null   object
 48  employment_status               2000 non-null   object
 49  location                        2000 non-null   object
 50  eligible_for_funding            2000 non-null   int64
 51  default_risk                    1980 non-null   object
 52  business_health_score           2000 non-null   float64
dtypes: float64(17), int64(26), object(10)
memory usage: 828.2+ KB

In [19]:
df.describe()

,sme_id,revenue,profit_margin,debt_ratio,collateral_value,marketing_spend,employee_count,age_of_business,previous_funding_received,previous_funding_amount,...,total_customers,active_customers,repeat_customers,campaign_spend,clicks,impressions,conversions,owner_age,eligible_for_funding,business_health_score
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,64560.036982,0.149889,0.294481,9850.166223,202.366843,49.445500,12.521500,0.398500,253246.554280,...,2571.623500,2020.377500,1521.814000,25648.870176,2481.09200,50081.593000,247.563500,39.731500,0.652500,56.753600
std,577.494589,47477.643644,0.069553,0.146069,25852.891789,182.091222,28.330731,6.933006,0.489712,142273.282611,...,1423.701863,1159.961812,860.991113,14146.281213,1448.95646,28474.623977,147.756059,11.572267,0.476295,16.505528
min,1.000000,30000.000000,0.000000,0.000000,11.792362,6.437111,1.000000,1.000000,0.000000,10163.154264,...,50.000000,21.000000,10.000000,1054.961060,11.00000,237.000000,0.000000,20.000000,0.000000,6.800000
25%,500.750000,40247.506821,0.100361,0.196981,1004.257571,88.965720,25.000000,7.000000,0.000000,129290.662381,...,1344.250000,1004.000000,790.250000,13258.683894,1210.50000,26700.500000,115.750000,29.000000,0.000000,46.000000
50%,1000.500000,50737.939603,0.149996,0.295469,2847.546163,150.108480,49.500000,13.000000,0.000000,248716.469838,...,2612.000000,2021.500000,1501.500000,25777.316289,2463.00000,50404.000000,244.000000,40.000000,1.000000,54.500000
75%,1500.250000,69981.600830,0.196588,0.394323,8652.169134,252.149193,74.000000,19.000000,1.000000,378857.364655,...,3795.500000,3071.000000,2265.000000,38016.296241,3704.50000,74434.500000,379.000000,50.000000,1.000000,64.100000
max,2000.000000,1000000.000000,0.424837,0.766937,593375.549170,2212.561859,99.000000,24.000000,1.000000,499746.524972,...,4998.000000,3999.000000,2999.000000,49994.752911,4999.00000,99891.000000,499.000000,59.000000,1.000000,100.000000

In [20]:
df.isnull().sum().sum()

np.int64(20)

In [22]:
df.isnull().sum()

sme_id                             0
business_name                      0
revenue                            0
profit_margin                      0
debt_ratio                         0
collateral_value                   0
marketing_spend                    0
employee_count                     0
age_of_business                    0
sector                             0
previous_funding_received          0
previous_funding_amount            0
default_history                    0
loan_applications_count            0
funding_requested_amount           0
expected_roi                       0
project_duration_months            0
business_stage                     0
collateral_offered                 0
business_registration_uploaded     0
tax_clearance_uploaded             0
financial_statements_uploaded      0
tax_registered                     0
tax_paid_last_year                 0
licenses_required                  0
licenses_up_to_date                0
staff_count                        0
total_payroll                      0
cost_per_hire                      0
nssf_contribution_percent          0
nhif_contribution_percent          0
staff_turnover_rate                0
bank_balance                       0
m_pesa_balance                     0
pending_invoices                   0
paid_invoices                      0
total_customers                    0
active_customers                   0
repeat_customers                   0
channels_used                      0
campaign_spend                     0
clicks                             0
impressions                        0
conversions                        0
target_segment                     0
owner_age                          0
owner_gender                       0
education_level                    0
employment_status                  0
location                           0
eligible_for_funding               0
default_risk                      20
business_health_score              0
dtype: int64

In [ ]:
df.fillna